version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: sykell_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: sykell_db
      MYSQL_USER: sykell_user
      MYSQL_PASSWORD: sykell_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - sykell_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: sykell_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "8081:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sykell_network

  # Temporal server using MySQL
  temporal:
    image: temporalio/auto-setup:1.22.0
    container_name: sykell_temporal
    restart: unless-stopped
    environment:
      - DB=mysql
      - DB_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PWD=rootpassword
      - MYSQL_SEEDS=mysql
      - MYSQL_DATABASE=temporal
    ports:
      - "7233:7233"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - sykell_network
    healthcheck:
      test: ["CMD", "tctl", "--address", "temporal:7233", "workflow", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 90s

  # Temporal Web UI
  temporal-web:
    image: temporalio/web:1.15.0
    container_name: sykell_temporal_web
    restart: unless-stopped
    environment:
      - TEMPORAL_GRPC_ENDPOINT=temporal:7233
      - TEMPORAL_PERMIT_WRITE_API=true
    ports:
      - "8088:8088"
    depends_on:
      temporal:
        condition: service_healthy
    networks:
      - sykell_network

volumes:
  mysql_data:
    driver: local

networks:
  sykell_network:
    driver: bridge


